# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'


- task: Bash@3
  inputs:
    targetType: 'inline'
    script: '''env | sort'''

- task: ArtifactoryMaven@2
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'install'
    artifactoryResolverService: 'Artifactory'
    targetResolveReleaseRepo: 'testjava-gradle-release'
    targetResolveSnapshotRepo: 'testjava-gradle-release'
    artifactoryDeployService: 'Artifactory'
    targetDeployReleaseRepo: 'testjava-gradle-dev-local'
    targetDeploySnapshotRepo: 'testjava-gradle-dev-local'

- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'Artifactory'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'