name: firstworkflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-shell-commands:
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run shell commands
        run: |
          echo "Hello, World!"
          echo "This is a simple shell command execution in GitHub Actions."
  build:
    runs-on: ubuntu-latest
 
